# Generated by Django 4.1.3 on 2022-12-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotation',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor'),
        ),
    ]
